CREATE TABLE AUTOR(
    ID NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    NOM varchar2(100),
    COGNOMS varchar2(200),
    DATA_NAIXAMENT date,
    NACIONALITAT varchar2 (3)
);

CREATE TABLE EDITORIAL(
    ID NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    NOM varchar2(50)
);

CREATE TABLE LLIBRE(
    ID NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    TITOL varchar2(50),
    ANYO date,
    EXEMPLARS NUMBER(10,0),
    ID_Editorial NUMBER NOT NULL REFERENCES EDITORIAL(ID),
    ID_Secuela NUMBER,
    FOREIGN KEY (ID_Secuela) REFERENCES LLIBRE (ID)
);

CREATE TABLE GENERE(
    ID NUMBER PRIMARY KEY
);

CREATE TABLE LLIBRE_GENERE(
    ID_LLIBRE NUMBER REFERENCES LLIBRE(ID),
    GENERE_NOM varchar2(30) REFERENCES GENERE(ID),
    PRIMARY KEY (ID_LLIBRE, GENERE_NOM)
);

CREATE TABLE LLIBRE_AUTOR(
    ID_AUTOR NUMBER,
    ID_LLIBRE NUMBER,
    PRIMARY KEY (ID_AUTOR, ID_LLIBRE),
    FOREIGN KEY (ID_AUTOR) REFERENCES AUTOR(ID),
    FOREIGN KEY (ID_LLIBRE) REFERENCES LLIBRE(ID)
);