DROP TABLE ACCIDENT_VEHICLE;
DROP TABLE MULTA;
DROP TABLE ACCIDENT;
DROP TABLE VEHICLE;
DROP TABLE PERSONA;

CREATE TABLE PERSONA (
    DNI VARCHAR2(9) PRIMARY KEY,
    NOM VARCHAR2(50),
    LLINATGES VARCHAR2(100),
    ADRECA VARCHAR2(100),
    CODI_POSTAL VARCHAR(5) CHECK (CODI_POSTAL != '07430'),
    TELEFON NUMBER(9),
    DATA_ALTA DATE
);

CREATE TABLE VEHICLE (
    MATRICULA VARCHAR2(7) PRIMARY KEY,
    MARCA VARCHAR2(30),
    MODEL_VEHICLE VARCHAR2(30),
    CHECK (SUBSTR(MODEL_VEHICLE, 1, 4) != 'RB19'),
    DNI VARCHAR2(9) NOT NULL,
    FOREIGN KEY (DNI) REFERENCES PERSONA(DNI)
);

CREATE TABLE MULTA (
    CODI NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    DATA_I_HORA DATE,
    LLOC VARCHAR2(100),
    IMPORT_MULTA NUMBER(10,2) CHECK (IMPORT_MULTA >= 100.00),
    MATRICULA_VEHICLE VARCHAR2(7),
    FOREIGN KEY (MATRICULA_VEHICLE) REFERENCES VEHICLE(MATRICULA)
);

CREATE TABLE ACCIDENT (
    CODI NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    LLOC VARCHAR2(100),
    DATA_I_HORA DATE
);

CREATE TABLE ACCIDENT_VEHICLE (
    MATRICULA_VEHICLE VARCHAR2(7) NOT NULL,
    CODI_ACCIDENT NUMBER NOT NULL,
    INFORME_PARTICIPACIO VARCHAR2(500),
    PRIMARY KEY (MATRICULA_VEHICLE, CODI_ACCIDENT),
    FOREIGN KEY (MATRICULA_VEHICLE) REFERENCES VEHICLE(MATRICULA),
    FOREIGN KEY (CODI_ACCIDENT) REFERENCES ACCIDENT(CODI)
);

INSERT INTO PERSONA VALUES('12345678A', 'Daniel Alejandro', 'Hidalgo', 'Carrer Av, Picasso', '07014', 605147569, TO_DATE('15-01-2026'));
INSERT INTO PERSONA VALUES('15875693G', 'Miki', 'Coll', 'Carrer Son Puig, 5', '07011', 698735468, TO_DATE('15-01-2026'));

INSERT INTO VEHICLE VALUES('5463LKP', 'Kia', 'Sportage', '12345678A');
INSERT INTO VEHICLE VALUES('9999ABC', 'Seat', 'Ibiza', '12345678A');
INSERT INTO VEHICLE VALUES('5232IBP', 'BWM', 'E36', '15875693G');

INSERT INTO MULTA (DATA_I_HORA, LLOC, IMPORT_MULTA, MATRICULA_VEHICLE) VALUES (TO_DATE('15-01-2026 23:31','DD-MM-YYYY HH24:MI'), 'Palma de Mallorca', 150.00, '5232IBP');

INSERT INTO ACCIDENT (LLOC, DATA_I_HORA) VALUES ('Palma de Mallorca', TO_DATE('15-01-2026 23:31','DD-MM-YYYY HH24:MI'));

INSERT INTO ACCIDENT_VEHICLE VALUES('5232IBP', 1, 'Ya no tiene el soporte de direccion');
INSERT INTO ACCIDENT_VEHICLE VALUES('5463LKP', 1, 'El vehiculo tiene un impacto en la puerta copiloto');

ALTER TABLE MULTA ADD data_pagament DATE;

ALTER TABLE ACCIDENT_VEHICLE 
MODIFY INFORME_PARTICIPACIO VARCHAR2(2000);

ALTER TABLE PERSONA DROP COLUMN data_alta;

UPDATE PERSONA SET nom = 'Juanjo' WHERE dni = '12345678A';

DELETE FROM MULTA WHERE MATRICULA_VEHICLE = '5232IBP';
